let videoJuego = prompt ("¿Que tipo de video juegos te gusta?")

if(videoJuego.toUpperCase() == "ACCION") {
    alert ("Un videojuego de acción es un videojuego en el que el jugador debe usar su velocidad, destreza y tiempo de reacción. Entre los diversos géneros de videojuegos, el género de acción es el más amplio y abarcativo, englobando muchos subgéneros como videojuegos de lucha, videojuegos de disparos en primera persona, beat 'em ups y videojuegos de plataformas. Muy a menudo, los videojuegos de acción usan la violencia como su principal característica de interacción, más específicamente el combate con armas de fuego o cuerpo a cuerpo." + " " + "Un ejemplo de juegos de" + " " + videoJuego + " " + "es God Of War 4")
} else if (videoJuego.toUpperCase() == "AVENTURA") {
    alert ("Son un género de videojuegos, caracterizados por la investigación, exploración, la solución de rompecabezas, la interacción con personajes del videojuego, y un enfoque en el relato en vez de desafíos basados en reflejos . Es importante observar que este término no tiene relación con las películas y novelas de aventura y no es indicativo del tema o del sujeto que trata. La vasta mayoría de videojuegos de aventura son videojuegos de computadora, aunque los videojuegos de aventura de videoconsola no son desconocidos por lo mucho." + " " + "Un ejemplo de juegos de" + " " + videoJuego + " " + "es The Legend Of Zelda")
}  else if (videoJuego.toUpperCase() == "SHOOTER"){
    alert("Los videojuegos de disparos, tiros o shooters conforman un género que engloba un amplio número de subgéneros que tienen la característica común de permitir controlar un personaje que, por norma general, dispone de un arma (mayoritariamente de fuego) que puede ser disparada a voluntad. Pertenecen al género de acción." + " " + "Un ejemplo de juegos de" + " " + videoJuego + " " + "es Counter Strike: Global Offensive")
} else if (videoJuego.toUpperCase() == "DEPORTES"){
    alert("Un videojuego de deportes es un videojuego de consola o de computadora que simula el campo de deportes tradicionales. Estos videojuegos son sumamente populares, el género incluye algunos de los videojuegos con más éxito de venta. Casi todos los deportes conocidos han sido recreados con un videojuego, incluyendo béisbol, fútbol, fútbol americano, boxeo, lucha libre, críquet, golf, básquetbol, hockey sobre hielo, bolos, rugby, caza, pesca, skate, artes marciales mixtas, tabla sobre nieve, etc." + " " + "Un ejemplo de juegos de" + " " + videoJuego + " " + "es el Fifa")
} else if(videoJuego.toUpperCase() == "ROL"){
    alert("Un juego de rol o JDR (traducción típica en español del inglés role-playing game o sus siglas RPG, literalmente «juego de interpretación de roles») es un juego en el que uno o más jugadores desempeñan un determinado rol, papel o personalidad. Cuando una persona hace el papel de X significa que está interpretando el papel de un personaje jugador (término generalmente abreviado con la sigla «PJ»). Esta técnica es útil para manejar aspectos o temas difíciles en los que es necesario tomar diferentes posiciones para su mejor comprensión. Consiste en la representación espontánea de una situación real o hipotética para mostrar un problema o información relevante. De este modo pueden abordar la problemática desde diferentes perspectivas y comprender las diversas interpretaciones de una misma realidad." + " " + "Un ejemplo de juegos de" + " " + videoJuego + " " + "es World Of Warcraft")
} else if(videoJuego.toUpperCase() == "CARRERAS"){
    alert("Un videojuego de carreras es un videojuego en el que se imitan competencias entre vehículos. Usualmente el objetivo es recorrer cierta distancia o ir de un sitio hacia otro en el menor tiempo posible, como en el automovilismo y el motociclismo (los que generalmente son imitados). A pesar de que existen juegos de mesa de este tipo, el término generalmente se refiere a videojuegos." + " " + "Un ejemplo de juegos de" + " " + videoJuego + " " + "es Gran turismo")
} else if(videoJuego.toUpperCase() == "ESTRATEGIAS"){
    alert("Los videojuegos de estrategia son videojuegos que requieren que el jugador ponga en práctica sus habilidades de planeamiento y pensamiento para maniobrar, gestionando recursos de diverso tipo (materiales, humanos, militares...) para conseguir la victoria. En la mayoría de los videojuegos de estrategia al jugador se le concede una vista del mundo absoluta, controlando indirectamente las unidades bajo su poder." + " " + "Un ejemplo de juegos de" + " " + videoJuego + " " + "es Age Of Empires II")
}